name: Deploy Job Board

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy with Ansible
      run: |
        pip install ansible
        cd infra
         # Create temporary vault password file
        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_pass
        chmod 600 /tmp/vault_pass

        ansible-playbook -i hosts.yml playbook.yml \
          --vault-password-file /tmp/vault_pass

        # Clean up
        rm -f /tmp/vault_pass
