name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"

    - name: Lint
      run: |
        pip install ruff
        ruff check .
        ruff format --check .

    - name: Tests
      run: |
        pip install -e ".[dev]"
        coverage run -m pytest
        coverage report
