name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: ikalnytskyi/action-setup-postgres@v7
      with:
      # picked up from .test.env file
        username: tester
        password: password
        database: test_job_board
        port: 5432
        postgres-version: "16"
        ssl: true
      id: postgres

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"

    - name: Tests
      env:
        ENV: test
      run: |
        pip install -e ".[dev]"
        coverage run -m pytest
        coverage xml

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: coverage.xml

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-data

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
