name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tailwind-css-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Tailwind CSS
        run: bash scripts/build-tailwind.sh

      - name: Check if CSS is up to date
        run: |
          if ! git diff --exit-code job_board/static/css/output.css; then
            echo "❌ Tailwind CSS output.css is not up to date!"
            echo "Please run 'bash scripts/build-tailwind.sh' and commit the changes."
            echo "Or ensure your pre-commit hooks are installed: 'pre-commit install'"
            exit 1
          else
            echo "✅ Tailwind CSS output.css is up to date!"
          fi

  python-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: ikalnytskyi/action-setup-postgres@v7
      with:
      # picked up from .test.env file
        username: tester
        password: password
        database: test_job_board
        port: 5432
        postgres-version: "16"
        ssl: true
      id: postgres

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"

    - name: Tests
      env:
        ENV: test
      run: |
        pip install -e ".[dev]"
        coverage run -m pytest
        coverage xml

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-coverage-data
        path: coverage.xml

  javascript-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run JavaScript tests with coverage
      run: npm run test:coverage

    - name: Check JS coverage threshold
      run: |
        echo "✅ JavaScript tests completed successfully!"
        echo "📊 Coverage report:"
        if [ -f coverage/lcov.info ]; then
          echo "Coverage file generated: coverage/lcov.info"
          echo "✅ Coverage threshold (99%) met"
        else
          echo "❌ Coverage file not found"
          exit 1
        fi

    - name: Upload JS coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: js-coverage-data
        path: coverage/

  coverage:
    needs: [python-tests, javascript-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Python coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: python-coverage-data

      - name: Download JavaScript coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: js-coverage-data

      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
          flags: python

      - name: Upload JavaScript coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
          flags: javascript
