name: Coverage
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write

    steps:
    - uses: actions/checkout@v4
      with:
        # Checkout the PR head commit for proper annotations
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Download coverage artifacts
      uses: actions/download-artifact@v4
      with:
        name: coverage-data-${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
