name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Copy code to server
      run: |
        # Ensure the target directory exists
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "mkdir -p ${{ secrets.APP_DIR }}"
        rsync -avz --exclude '.git' --exclude 'venv' --exclude '.env' ./ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.APP_DIR }}/

    - name: Run deployment
      run: |
        # force ssh to allocate a pseudo-terminal
        ssh -tt ${{ secrets.USER }}@${{ secrets.HOST }} '
        cd ${{ secrets.APP_DIR }}
        bash deploy.sh
        '
